config/routes.rb
DannysDream::Application.routes.draw do
  
  # Footer
    match "/accessibility" => "application#accessibility"
    match "/site_map" => "application#site_map"
  
  resources :articles
  resources :calendar_entries, :only => [:index]
  resources :contacts, :only => [:new, :create] do
    get "thanks", :on => :collection
  end
  resources :gallery_images, :only => [:index]
  resources :links, :only => [:index]
  resources :pages
  resources :points_of_contact, :only => [:index]
  resources :testimonials, :only => [:index]
  resources :websites, :only => [:index]
  
  namespace :admin do
    chronicler_resources :articles
    chronicler_resources :gallery_images
    chronicler_resources :links
    chronicler_resources :pages
    manticore_resources  :calendar_entries
    manticore_resources  :point_of_contacts
    manticore_resources  :testimonials
    manticore_resources  :websites
  end
  
  root :to => "pages#show", :id => "welcome-to-danny-s-dream"
  
  mount Manticore::Engine => "/admin"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  mount_uploader :image, ArticleImageUploader

  scope :front_end, :conditions => {:display => true}, :order => "date DESC"
  
end

app/controllers/admin/articles_controller.rb
module Admin
  
  class ArticlesController < Manticore::ApplicationController
    
    crops_images_for Article, :image, { :show => { :fit => [300, 1000] } }
    
    def index
      @articles = Article.all
    end
    
    def new
      @article = Article.new
    end
    
    def create
      @article = Article.new(params[:article])
      if @article.save
        redirect_to admin_articles_path, :notice => "Article successfully created."
      else
        render :action => 'new'
      end
    end
    
    def edit
      @article = Article.find(params[:id])
    end
    
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        redirect_to admin_articles_path, :notice => "Article successfully updated."
      else
        render :action => 'edit'
      end
    end
    
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to admin_articles_path, :notice => "Article destroyed."
    end
    
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.front_end
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
end

app/views/admin/articles/_form.html.erb
<%= form_for([:admin, @article]) do |f| %>

  <%= f.error_messages %>

  <%= field_set_tag("Basic Information") do %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :summary %><br />
      <%= f.text_area :summary %>
    </div>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content, :class => "tinymce" %>
    </div>
    <div class="field">
      <%= f.label :date %><br />
      <%= f.date_select :date %>
    </div>
  <% end %>

  <%= field_set_tag("Image") do %>
    <div class="field">
      <%= f.image_field :image %>
    </div>
    <div class="field">
      <%= f.label :image_alt %><br />
      <%= f.text_field :image_alt %>
    </div>
  <% end %>

  <div class="field">
    <%= f.check_box :display %>
    <%= f.label :display %>
  </div>

  <br />

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/articles/edit.html.erb
<% title "Edit #{Article.model_name.titleize}" %>

<div class="admin_functions">
  <%= link_to "Back", admin_articles_path %>
</div>

<%= render 'form' %>

app/views/admin/articles/index.html.erb
<% title Article.model_name.titleize.pluralize %>

<div class="admin_functions">
  <%= link_to "New #{Article.model_name.titleize}", new_admin_article_path %>
</div>

<%= informant_table @articles, {
    :headings => [ 'Name', 'Summary', 'Date', 'Displayed?', '', '', '' ], 
    :body     => [ :name, lambda{|a| a.summary.length > 79 ? strip_tags(a.summary)[0..79] + "..." : strip_tags(a.summary)}, lambda{|a| l(a.date, :format => :short)}, it_ajax_toggle(:display), it_edit_images, it_edit, it_destroy ]
  } %>

app/views/admin/articles/new.html.erb
<% title "New #{Article.model_name.titleize}" %>

<div class="admin_functions">
  <%= link_to "Back", admin_articles_path %>
</div>

<%= render 'form' %>