config/routes.rb
DannysDream::Application.routes.draw do
  
  # Footer
    match "/accessibility" => "application#accessibility"
    match "/site_map" => "application#site_map"
  
  resources :articles
  resources :calendar_entries, :only => [:index]
  resources :contacts, :only => [:new, :create] do
    get "thanks", :on => :collection
  end
  resources :gallery_images, :only => [:index]
  resources :links, :only => [:index]
  resources :pages
  resources :points_of_contact, :only => [:index]
  resources :testimonials, :only => [:index]
  resources :websites, :only => [:index]
  
  namespace :admin do
    chronicler_resources :articles
    chronicler_resources :gallery_images
    chronicler_resources :links
    chronicler_resources :pages
    manticore_resources  :calendar_entries
    manticore_resources  :point_of_contacts
    manticore_resources  :testimonials
    manticore_resources  :websites
  end
  
  root :to => "pages#show", :id => "welcome-to-danny-s-dream"
  
  mount Manticore::Engine => "/admin"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  mount_uploader :image, ArticleImageUploader

  scope :front_end, :conditions => {:display => true}, :order => "date DESC"
  
end

app/controllers/admin/articles_controller.rb
module Admin
  
  class ArticlesController < Manticore::ApplicationController
    
    crops_images_for Article, :image, { :show => { :fit => [300, 1000] } }
    
    def index
      @articles = Article.all
    end
    
    def new
      @article = Article.new
    end
    
    def create
      @article = Article.new(params[:article])
      if @article.save
        redirect_to admin_articles_path, :notice => "Article successfully created."
      else
        render :action => 'new'
      end
    end
    
    def edit
      @article = Article.find(params[:id])
    end
    
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        redirect_to admin_articles_path, :notice => "Article successfully updated."
      else
        render :action => 'edit'
      end
    end
    
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to admin_articles_path, :notice => "Article destroyed."
    end
    
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.front_end
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
end

app/views/articles/_basic_page.html.erb
<h2>News <%= link_to "View All", articles_path, :class => "view_all" %></h2>
<% @articles ||= Article.front_end %>
<% if !@articles.empty? %>
  <div id="articles">
    <% @articles.each_with_index do |a, i| %>
      <div class="article">
        <%= link_to(image_tag(a.image.home, :alt => a.image_alt, :title => a.image_alt, :class => "article_image"), article_path(a)) if a.image? %>
        <div class="article_details">
          <span class="article_date"><%= l(a.date, :format => :long) %></span>
          <p><%= a.summary %></p>
          <p><%= link_to "Read more", article_path(a) %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No news to display - check back soon!</p>
<% end %>

app/views/articles/index.html.erb
<% content_for :head, stylesheet_link_tag("articles") %>
<div class="col_12">
  <h1><%= title("News") %></h1>
  <div id="articles">
    <% @articles.each do |a| %>
      <div class="article">
        <%= link_to(image_tag(a.image.index, :alt => a.image_alt, :title => a.image_alt, :class => "article_image"), article_path(a)) if a.image? %>
        <div class="article_details">
          <h2><%= a.name %></h2>
          <span class="article_date"><%= l(a.date, :format => :long) %></span>
          <p><%= a.summary %></p>
          <p><%= link_to "Read more", article_path(a) %></p>
        </div>
      </div>
      <div class="clear"></div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<% content_for :head, stylesheet_link_tag("articles") %>
<div class="col_12">
  <h1><%= title("News - #{@article.name}") %></h1>
  <div class="article">
    <%= image_tag(@article.image.show, :class => "article_image") %>
    <%= raw(@article.content) %>
  </div>
</div>