config/routes.rb
DannysDream::Application.routes.draw do
  
  # Footer
    match "/accessibility" => "application#accessibility"
    match "/site_map" => "application#site_map"
  
  resources :articles
  resources :calendar_entries, :only => [:index]
  resources :contacts, :only => [:new, :create] do
    get "thanks", :on => :collection
  end
  resources :gallery_images, :only => [:index]
  resources :links, :only => [:index]
  resources :pages
  resources :points_of_contact, :only => [:index]
  resources :testimonials, :only => [:index]
  resources :websites, :only => [:index]
  
  namespace :admin do
    chronicler_resources :articles
    chronicler_resources :gallery_images
    chronicler_resources :links
    chronicler_resources :pages
    manticore_resources  :calendar_entries
    manticore_resources  :point_of_contacts
    manticore_resources  :testimonials
    manticore_resources  :websites
  end
  
  root :to => "pages#show", :id => "welcome-to-danny-s-dream"
  
  mount Manticore::Engine => "/admin"
  
end

app/models/calendar_entry.rb
class CalendarEntry < ActiveRecord::Base
  
  validates :name,
    {:presence => true}
  validates :date,
    {:presence => true}
  validates :content,
    {:presence => true}
  
  scope :front_end, lambda{ where("display = true AND date >= ?", Date.today).order("date") }
  
end

app/controllers/admin/calendar_entries_controller.rb
module Admin
  
  class CalendarEntriesController < Manticore::ApplicationController
    
    def index
      @calendar_entries = CalendarEntry.all
    end
    
    def new
      @calendar_entry = CalendarEntry.new
    end
    
    def create
      @calendar_entry = CalendarEntry.new(params[:calendar_entry])
      if @calendar_entry.save
        redirect_to admin_calendar_entries_path, :notice => "Calendar Entry successfully created."
      else
        render :action => 'new'
      end
    end
    
    def edit
      @calendar_entry = CalendarEntry.find(params[:id])
    end
    
    def update
      @calendar_entry = CalendarEntry.find(params[:id])
      if @calendar_entry.update_attributes(params[:calendar_entry])
        redirect_to admin_calendar_entries_path, :notice => "Calendar Entry successfully updated."
      else
        render :action => 'edit'
      end
    end
    
    def destroy
      @calendar_entry = CalendarEntry.find(params[:id])
      @calendar_entry.destroy
      redirect_to admin_calendar_entries_path, :notice => "Calendar Entry destroyed."
    end
    
  end
  
end

app/controllers/calendar_entries_controller.rb
class CalendarEntriesController < ApplicationController
  
  def index
    @calendar_entries = CalendarEntry.front_end
  end
  
end

app/views/calendar_entries/_basic_page.html.erb
<h2>Calendar <%= link_to "View All", calendar_entries_path, :class => "view_all" %></h2>
<% @entries ||= CalendarEntry.front_end %>
<% if !@entries.empty? %>
  <% @entries[0..1].each_with_index do |e, i| %>
    <div class="event_frame">
      <div class="date">
        <%= calendar_entry_date(e.date) %>
      </div>
      <div class="text">
        <span class="title">
          <%= e.name %><br />
        </span>
        <span class="content">
          <%= strip_tags(e.content).length > 137 ? strip_tags(e.content[0..136] + "...") : strip_tags(e.content) %>
        </span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/calendar_entries/_home_page.html.erb
<h2>Calendar <%= link_to "View All", calendar_entries_path, :class => "view_all" %></h2>
<% @entries ||= CalendarEntry.front_end %>
<% if !@entries.empty? %>
  <% @entries[0..1].each_with_index do |e, i| %>
    <div class="home_event_frame">
      <div class="date">
        <%= calendar_entry_date(e.date) %>
      </div>
      <div class="text">
        <span class="title">
          <%= e.name %><br />
        </span>
        <span class="content">
          <%= strip_tags(e.content).length > 137 ? strip_tags(e.content[0..136] + "...") : strip_tags(e.content) %>
        </span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/calendar_entries/index.html.erb
<div class="col_12">
  
  <h1><%= title(CalendarEntry.model_name.titleize.pluralize) %></h1>

  <% @calendar_entries.each_with_index do |c, i| %>
    <div style="margin: 10px auto 10px auto;">
      <h2><%= c.name %></h2>
      <%= l(c.date, :format => :long) %>
      <%= raw(c.content) %>
    </div>
  <% end %>
  
</div>