config/routes.rb
DannysDream::Application.routes.draw do
  
  # Footer
    match "/accessibility" => "application#accessibility"
    match "/site_map" => "application#site_map"
  
  resources :articles
  resources :calendar_entries, :only => [:index]
  resources :contacts, :only => [:new, :create] do
    get "thanks", :on => :collection
  end
  resources :gallery_images, :only => [:index]
  resources :links, :only => [:index]
  resources :pages
  resources :points_of_contact, :only => [:index]
  resources :testimonials, :only => [:index]
  resources :websites, :only => [:index]
  
  namespace :admin do
    chronicler_resources :articles
    chronicler_resources :gallery_images
    chronicler_resources :links
    chronicler_resources :pages
    manticore_resources  :calendar_entries
    manticore_resources  :point_of_contacts
    manticore_resources  :testimonials
    manticore_resources  :websites
  end
  
  root :to => "pages#show", :id => "welcome-to-danny-s-dream"
  
  mount Manticore::Engine => "/admin"
  
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  
  mount_uploader :image, GalleryImageImageUploader
  
  validates :image, :presence => true
  
  default_scope order(:position)
  scope :display, where(:display => true)
  
  def self.categories
    self.all.collect{|x| x.category }.uniq.reject{|x| x.blank?}.sort
  end
  
end

app/controllers/admin/gallery_images_controller.rb
module Admin
  class GalleryImagesController < Manticore::ApplicationController
    
    crops_images_for GalleryImage, :image
  
    def index
      @gallery_images = GalleryImage.all
    end
    
    def new
      @gallery_image = GalleryImage.new
    end
    
    def create
      @gallery_image = GalleryImage.new(params[:gallery_image])
      if @gallery_image.save
        redirect_to admin_gallery_images_path, :notice => "Gallery image successfully created."
      else
        render :action => 'new'
      end
    end

    def edit
      @gallery_image = GalleryImage.find(params[:id])
    end
    
    def update
      @gallery_image = GalleryImage.find(params[:id])
      if @gallery_image.update_attributes(params[:gallery_image])
        redirect_to admin_gallery_images_path, :notice => "Gallery image successfully updated."
      else
        render :action => 'edit'
      end
    end
    
    def destroy
      @gallery_image = GalleryImage.find(params[:id])
      @gallery_image.destroy
      redirect_to admin_gallery_images_path, :notice => "Gallery image destroyed."
    end
    
  end
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  
  before_filter do 
    @current_branch = Willow::StaticPage.find_by_name("Gallery").try(:branch)
  end
  
  def index
    @gallery_images = GalleryImage.display
    if params[:category]
      @gallery_images = @gallery_images.where(["category = ?", params[:category]])
    end
  end

end

app/views/admin/gallery_images/_form.html.erb
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("input#gallery_image_category").autocomplete({
      source: [<%= GalleryImage.categories.map{|x| "'#{x}\'"}.join(",") %>],
      delay: 0,
      minLength: 0
    });
    $('input#gallery_image_category').focus(function(){
      $(this).autocomplete('search');
    });
  });
</script>

<%= form_for([:admin, @gallery_image]) do |f| %>

  <%= f.error_messages %>

  <%= field_set_tag("Basic Information") do -%>
    <div class="field">
      <%= f.image_field :image %>
    </div>
    <div class="field">
      <%= f.label :alt, "Image alt" %><br />
      <%= f.text_field :alt %>
    </div>
  <% end -%>

  <%= field_set_tag("Category") do -%>
    <div class="field">
      <%= f.text_field :category %>
    </div>
  <% end %>

  <div class="field">
    <%= f.check_box :display %>
    <%= f.label :display %>
  </div>

  <br />

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/gallery_images/edit.html.erb
<% title "Edit #{GalleryImage.model_name.titleize}" %>

<div class="admin_functions">
  <%= link_to "Back", admin_gallery_images_path %>
</div>

<%= render 'form' %>

app/views/admin/gallery_images/index.html.erb
<% title GalleryImage.model_name.titleize.pluralize %>

<div class="admin_functions">
  <%= link_to "New #{GalleryImage.model_name.titleize}", new_admin_gallery_image_path %>
</div>

<%= informant_table @gallery_images, {
    :headings => [ '', 'Image', 'Alt', 'Category', 'Display', '', '', '' ], 
    :body     => [ it_sort, it_thumb(:image), :alt, :category, it_ajax_toggle(:display), it_edit_images, it_edit, it_destroy ]
  } %>

app/views/admin/gallery_images/new.html.erb
<% title "New #{GalleryImage.model_name.titleize}" %>

<div class="admin_functions">
  <%= link_to "Back", admin_gallery_images_path %>
</div>

<%= render 'form' %>